name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET app
        run: dotnet publish poc-msa-interoperability-netService.sln -c Release -o publish

      - name: Zip publish output
        run: zip -r app.zip publish/*

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: poc-msa-interoperability-net
          environment_name: Poc-msa-interoperability-net-env
          region: us-east-1
          version_label: ${{ github.run_id }}
          deployment_package: app.zip
